Develop/fsi reweight
GENIE-MC/Generator pull request #170
Opened 2021-08-02 10:12 UTC by jtenavidal

2021-08-03 11:21 UTC, jtenavidal commented
I tested it locally and it follows the expected behavior. I will now test it with GENIE Comparisons. Focus on Minerva data, pi+ absorbtion and pion inel events. Will add the results here when available.

2021-08-09 10:15 UTC, mroda88 requested changes
glad it works. Some logic and code fixing necessary.

2021-08-09 10:15 UTC, mroda88 commented on src/Physics/HadronTransport/CascadeReweight.cxx
> +  GetParamDef( "CascadeReweight-Default-Weight", fDefaultWeight, 1. ) ;
this needs to go

2021-08-09 10:15 UTC, mroda88 commented on src/Physics/HadronTransport/INukeHadroFates2018.h
> +  static std::map<INukeFateHN_t,string> GetEINukeFateKeysMap( void ) {
Because this map is inconsistent with the rest, we should move it to the CascateReweight header.

2021-08-09 10:15 UTC, mroda88 commented on src/Physics/HadronTransport/INukeHadroFates2018.h
> +  static std::map<INukeFateHN_t,string> GetEINukeFateKeysMap( void ) {
since the map itself is static, you can probably return a reference in this case.

2021-08-09 10:15 UTC, mroda88 commented on src/Physics/HadronTransport/INukeHadroFates2018.h
> +    static std::map<INukeFateHN_t,string> map_keys { {kIHNFtUndefined,"Undefined"}, {kIHNFtNoInteraction,"NoInteraction"},
the map has to `const` and so the returned type

2021-08-09 10:15 UTC, mroda88 commented on src/Physics/HadronTransport/HadronTransporter.cxx
> +       LOG("HadronTransporter", pERROR) << "Configuration has failed.";
This is a `pFATAL`

2021-08-09 10:15 UTC, mroda88 commented on src/Physics/HadronTransport/CascadeReweight.cxx
> +  std::map<INukeFateHN_t,string> EINukeFate_map_keys = INukeHadroFates::GetEINukeFateKeysMap() ;
The new map now will be in the CascadeReweight namespace

2021-08-09 10:15 UTC, mroda88 commented on src/Physics/HadronTransport/CascadeReweight.cxx
> +    std::map<int,double> WeightMap ; // define map that stores <pdg, weight>
This variable should be defined inside the loop

2021-08-09 10:15 UTC, mroda88 commented on src/Physics/HadronTransport/CascadeReweight.cxx
> +    fFateWeightsMap[it_keys->first] = WeightMap ;
```c++
 fFateWeightsMap[it_keys->first] = std::move(WeightMap) ; 
```

2021-08-16 10:04 UTC, mroda88 requested changes
Just small fixes and then we are good to go

2021-08-16 10:04 UTC, mroda88 commented on config/CascadeReweight.xml
> +Configuration sets for the CascadeReweight EventRecordVisitorI
here add a line saying that clearly this configuration file is done for tuning purposes, and the present configurations are here only as an example

2021-09-14 10:54 UTC, mroda88 approved these changes
It will probably not be used anytime soon, but the interface is very clean and can be used as a base for future works.

2021-09-14 10:54 UTC, merged