Origin/develop/mec scale vs w edges
GENIE-MC/Generator pull request #189
Opened 2021-11-04 18:40 UTC by jtenavidal

In order to implement the new parameterization of the MECScaleVsW that we suggested in the last meeting, we need to be able to set the weight for both edges. In the previous implementation, this was the same parameter, defined by the default.

2021-11-04 20:55 UTC, jtenavidal commented
Code tested. Works fine.

2021-11-08 10:50 UTC, mroda88 requested changes
Please do those small changes

2021-11-08 10:50 UTC, mroda88 commented on src/Physics/Multinucleon/XSection/MECScaleVsW.cxx
> +  if( GetConfig().Exists("MECScleVsW-LowerLimit-Weight") ) {
Instead of this very verbose block, 
please do this
```C++
GetParamDef("MECScleVsW-LowerLimit-Weight", fLowLimitWeight, fDefaultWeight ) ; 
```

2021-11-08 10:50 UTC, mroda88 commented on src/Physics/Multinucleon/XSection/MECScaleVsW.cxx
> +  if( GetConfig().Exists("MECScleVsW-UpperLimit-Weight") ) {
Same as the previous block

2021-11-08 11:56 UTC, mroda88 approved these changes
Great

2021-11-08 11:56 UTC, merged