Develop/export bs xml
GENIE-MC/Generator pull request #352
Opened 2023-10-30 13:57 UTC by feuerbutter

put the 4 parameters in the BergerSehgalRESPXSec2014.cxx vector current form factor calculation into BergerSehgalRESPXSec2014.xml . they are now called fCv3,4,51,52

2023-11-01 10:44 UTC, mroda88 requested changes
- add parameters description in the xml file top table.
- Expose also the hardcoded CA5_0 (from the axial current)

2023-11-01 11:31 UTC, idkakorin commented
For uniformity, it is necessary to do the same in the MKSPPPXSec2020 model.

2023-11-01 11:38 UTC, idkakorin requested changes
https://github.com/GENIE-MC/Generator/pull/352#issuecomment-1788805265

2023-11-02 15:40 UTC, idkakorin commented on src/Physics/Resonance/XSection/MKSPPPXSec2020.cxx
LGTM

2023-11-02 15:40 UTC, idkakorin commented on src/Physics/Resonance/XSection/MKSPPPXSec2020.h
LGTM

2023-11-02 15:41 UTC, idkakorin approved these changes

2023-11-09 10:34 UTC, mroda88 approved these changes
Great

2023-11-09 10:35 UTC, merged